# Only build tags:
# if: tag IS present

os:
  - windows
  - linux
  - osx

dist: xenial

language: shell

notifications:
  email: false

git:
  submodules: false

# Install packages
install:
  - _py_ver="3.7"
  - |
    if [ "$TRAVIS_OS_NAME" = 'windows' ]; then
        choco install miniconda3
        _pref="/c/tools/miniconda3"
        export PATH="$_pref:$_pref/Scripts:$_pref/condabin:$PATH"
    elif [ "$TRAVIS_OS_NAME" = 'osx' ]; then
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        _pref="--yes"
    else
        sudo apt-get update
        sudo apt-get install -y libatk-bridge2.0-0 libgtk-3.0
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        _pref="--yes"
    fi
  - hash -r
  - source activate base
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda update -y conda
  # Useful for debugging any issues with conda
  - conda info -a
  - |
    conda create -y -n test-pandoctools "python=$_py_ver" "pip>=10.0.1" click pyyaml notebook jupyter \
    libsass "shutilwhich-cwdpatch>=0.1.0" "panflute>=1.12.4" "knitty>=0.5.0" "pyppdf>=0.0.11" \
    "py-mathjax<3.0" "sugartex>=0.1.16" "shortcutter>=0.1.19" "numpy" "py-pandoc>=2.8.0.1" \
    "py-pandoc-crossref>=0.3.5.0.1" "jupyter_console>=6.0.0"
  - git clone https://github.com/kiwi0fruit/pyappshare
  - git clone https://github.com/kiwi0fruit/sugartex
  - git clone https://github.com/back0up/pandoctools-ci
  - bash ./pyappshare/other_envs/python3/install "${_pref}"
  - bash ./pyappshare/other_envs/r/install "${_pref}"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis-CI"
  - source activate test-pandoctools
  - pip install "py-open-fonts>=0.4.9"
  - jupyter kernelspec list
  - pip install -e .
  - pandoctools-ready
  - rm ./examples/doc.ipynb
  - rm ./examples/doc.pdf
  - rm ./examples/notebook.ipynb
  - rm ./examples/notebook.pdf
  - rm ./sugartex/examples/examples.pdf

# Run test
script:
  - pandoctools --yes ./examples/doc.md
  - pandoctools --yes ./examples/doc.md -o "*.pdf"
  - pandoctools --yes ./examples/notebook.py
  - pandoctools --yes ./examples/notebook.py -o "*.pdf"
  - pandoctools --yes ./sugartex/examples/examples.md -o "*.ipynb"
  - pandoctools --yes ./sugartex/examples/examples.md -o "*.pdf"
  - cd ./pandoctools-ci
  - git pull
  - git pull
  - rm -rf ./$TRAVIS_OS_NAME
  - mkdir -p ./$TRAVIS_OS_NAME
  - cp ../examples/doc.pdf ./$TRAVIS_OS_NAME
  - cp ../examples/doc.ipynb ./$TRAVIS_OS_NAME
  - cp ../examples/notebook.pdf ./$TRAVIS_OS_NAME
  - cp ../examples/notebook.ipynb ./$TRAVIS_OS_NAME
  - cp ../sugartex/examples/examples.pdf ./$TRAVIS_OS_NAME
  - cp ../sugartex/examples/examples.ipynb ./$TRAVIS_OS_NAME
  - git add .
  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
  - git push "https://${back0up_PAT}@github.com/back0up/pandoctools-ci.git" master > /dev/null 2>&1
