{% set name = "pandoctools" %}
{% set version = "2.8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edea498d4e4ab83fe5b1cb358ecb87e85c47eec2c30461426f5b7a2461bdbbc3

build:
  noarch: python
  number: 0
  entry_points:
    - cat-md = pandoctools.cat_md.cat_md:cli
    - pandoctools = pandoctools.cli.cli:pandoctools
    - pandoctools-resolve = pandoctools.pandoctools_resolve.resolve:cli
    - pandoctools-ready = pandoctools.ready.ready:ready
    - regex-replace = pandoctools.regex_replace.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip >=10.0.1
    - setuptools
    - click
    - pyyaml
    - notebook
    - jupyter
    - numpy
    - panflute >=1.12.4
    - knitty >=0.5.0
    - pyppdf >=0.0.11
    - sugartex >=0.1.16
    - shortcutter >=0.1.19
    - py-pandoc-crossref >=0.3.5.0.1
    - py-pandoc >=2.8.0.1
    - libsass
    - py-mathjax <3.0
    - shutilwhich-cwdpatch >=0.1.0
    - jupyter_console >=6.0.0
    - py-open-fonts >=0.4.9

test:
  imports:
    - pandoctools
    - pandoctools.ready
    - pandoctools.shared_vars
    - pandoctools.pandoctools_resolve
    - pandoctools.cli
    - pandoctools.cat_md
    - pandoctools.regex_replace
  commands:
    - pandoctools --help
    - pandoctools-ready
    - pandoctools-resolve Default
    - regex-replace --help
    - |
      echo hello | cat-md - -

about:
  home: https://github.com/kiwi0fruit/pandoctools
  license: "GPL2+"
  license_family: GPL2
  license_file: LICENSE
  summary: "Profile manager of text processing pipelines: Pandoc filters, any text CLI filters. Atom+Markdown+Pandoc+Jupyter workflow, export to ipynb."
  doc_url: https://github.com/kiwi0fruit/pandoctools
  dev_url: https://github.com/kiwi0fruit/pandoctools

extra:
  recipe-maintainers:
    - kiwi0fruit
